import "@/assets/css/animate.min.css";
import "@/assets/css/dropdownmenu.css";
import "@/assets/css/sidebar.css";
import "@/assets/css/style.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.css";
import NextTopLoader from "nextjs-toploader";
import "react-quill/dist/quill.snow.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <NextTopLoader color="#e60000" height={2} speed={200} />
      </body>
    </html>
  );
}
